import Head from 'next/head'
import { useState, useEffect } from 'react'
import Header from '../components/Header/Header'
import Sidebar from '../components/Sidebar/Sidebar'
import Invoice from '../components/Invoice/Invoice'
import Footer from '../components/Footer/Footer'
import Button from '../components/Button/Button'
import Modal from '../components/Modal/Modal'
import styles from '../styles/Home.module.scss'

 const Home = () => {
  const [openModal, setOpenModal] = useState(false);
  return (
    <>
      <Head>
        <title>Invoice Tool | Joshua</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header Component => /components/Header/Header */}
      <Header />

      {/* Button Component => /components/Button/Button */}
      <Button onClick={()=> setOpenModal(true)} />

      {/* Modal is opened in the view after clicking Above button */}
       {openModal && <Modal closeModal={setOpenModal}/> }

      {/* Sidebar and Invoice Dashboard */}
      <div className={styles.container}>

        {/* Sidebar component => /components/Sidebar/Sidebar */}
        <Sidebar />

        {/* Invoice component => /components/Invoice/Invoice */}
        <main className={styles.main}>
          <Invoice />
        </main>
      </div>
    </>
  )
}
export default Home;